using System.Collections.Generic;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

public class CreatureVariantLabWindow : EditorWindow
{
    private static class Tips
{
    public const string Scene = "Runtime testing requires TestMapScene with RoomContext, RoomGrid and CombatRoomController.";
    public const string PlayMode = "Spawn, selection, combat and runtime logging require Play Mode.";
    public const string RuntimeContext = "Spawn requires RoomContext, RoomGrid and CombatRoomController in the active scene.";
    public const string Composition = "Errors prevent spawning. Warnings describe experimental behavior.";
    public const string Faction = "Selects the creature family and loads default stats from the creation preset.";
    public const string Role = "Selects the combat role and its allowed delivery patterns.";
    public const string Team = "Determines which side the test unit spawns on. Dummy spawns on the opposite side.";
    public const string UnitName = "Display name for this unit. Letters, numbers, spaces and underscores allowed.";
    public const string PrefabOverride = "Optional prefab override. If empty, a placeholder is generated for testing.";
    public const string ImportUnit = "Copies stats from an existing UnitData into the editor. No permanent dependency is created.";
    public const string MaxHp = "Maximum health points. Must be greater than 0.";
    public const string Damage = "Base attack damage per hit.";
    public const string Defense = "Damage reduction per hit.";
    public const string MoveSpeed = "Movement speed. Must be greater than 0.";
    public const string AttackRange = "Attack range in grid cells. Must be greater than 0.";
    public const string AttackCooldown = "Seconds between attacks. Must be greater than 0.";
    public const string Accuracy = "Hit chance (0 to 1).";
    public const string Evasion = "Dodge chance (0 to 1).";
    public const string VisionRange = "Detection range in grid cells. Must be greater than 0.";
    public const string ManaRecruit = "Mana cost to recruit this unit.";
    public const string ManaAbsorb = "Mana cost to absorb this unit's soul.";
    public const string Delivery = "Defines how targets are reached. Role restrictions are validated below.";
    public const string PrimaryTarget = "Defines the required initial target.";
    public const string Effect = "Selects the Skill Composition effect generated by this lab.";
    public const string Modifier = "Optional composition modifier.";
    public const string Status = "Runtime status behavior from this asset, including duration and tick interval.";
    public const string Value = "Magnitude applied by Damage, Heal, Shield or Heal Over Time.";
    public const string Duration = "Preview duration for shield/status composition.";
    public const string Interval = "Preview tick interval.";
    public const string Radius = "Area radius in grid cells. Must be greater than zero.";
    public const string LineLength = "Maximum line length in grid cells. Must be greater than zero.";
    public const string Range = "Maximum targeting range in grid cells.";
    public const string Knockback = "Number of grid cells the target is pushed.";
    public const string SummonedUnit = "UnitData spawned by the effect.";
    public const string SummonAnchor = "Controls where the summoned unit is placed relative to the impact.";
    public const string BounceCount = "Maximum additional targets.";
    public const string BounceRange = "Maximum search range between bounce targets.";
    public const string BouncePrimary = "Allows a bounce chain to return to the original target.";
    public const string ExplosiveRadius = "Secondary impact radius.";
    public const string ExplosivePrimary = "Includes the primary impact target in the explosion secondary target set.";
    public const string Validation = "Errors are blocking. Info messages are non-blocking notes.";
    public const string SpawnUnit = "Spawns a test unit with the current composition. Uses Team from Choose Creature.";
    public const string SpawnDummy = "Spawns a passive target on the opposite team near the test unit for manual skill casting.";
    public const string ClearUnits = "Removes all units spawned by the Lab and cleans up runtime data.";
    public const string SelectUnit = "Selects and pings the most recently spawned runtime unit.";
    public const string LogState = "Writes room, unit, health, team and skill charge state to the Console.";
    public const string ClearLegacyTemp = "Deletes legacy _LabTemp assets from disk. Only needed for cleanup from older versions.";
}

    [MenuItem("Tools/Creatures/Creature Variant Lab")]
    public static void ShowWindow()
    {
        GetWindow<CreatureVariantLabWindow>("Creature Variant Lab");
    }

    private CreatureVariantLabState _state = new CreatureVariantLabState();
    private CreatureVariantLabController _controller;
    private CreatureVariantLabConfig _config;

    private List<StatusEffectDefinition> _statusDefinitions = new List<StatusEffectDefinition>();
    private List<string> _statusNames = new List<string>();
    private int _selectedStatusIndex;

    private Vector2 _scrollPosition;
    private bool _showUnitStats = true;
    private bool _showAdvancedOverrides;
    private bool _showAdvancedWarnings;
    private bool _showRuntimeDetails;
    private bool _showAdvancedTools;
    private string _actionFeedback;
    private MessageType _actionFeedbackType = MessageType.Info;

    private GUIStyle _headerStyle;

    private void OnEnable()
    {
        LoadConfig();
        EnsureController();
        LoadStatusDefinitions();
        Validate();
        EditorApplication.playModeStateChanged += OnPlayModeStateChanged;
        EditorApplication.hierarchyChanged += OnHierarchyChanged;
        EditorApplication.projectChanged += OnProjectChanged;
        EditorSceneManager.activeSceneChangedInEditMode += OnSceneChanged;
        SceneManager.activeSceneChanged += OnActiveSceneChanged;
    }

    private void OnDisable()
    {
        EditorApplication.playModeStateChanged -= OnPlayModeStateChanged;
        EditorApplication.hierarchyChanged -= OnHierarchyChanged;
        EditorApplication.projectChanged -= OnProjectChanged;
        EditorSceneManager.activeSceneChangedInEditMode -= OnSceneChanged;
        SceneManager.activeSceneChanged -= OnActiveSceneChanged;
    }

    private void LoadConfig()
    {
        var result = CreatureVariantAssetService.FindOrCreateConfig();
        _config = result.config;

        if (result.status == CreatureVariantLabConfigValidator.ConfigStatus.Multiple)
        {
            _config = null;
            Debug.LogError($"[Creature Variant Lab] Multiple CreatureVariantLabConfig assets found. Remove duplicates:\n{result.message}");
        }
    }

    private void EnsureController()
    {
        if (_controller == null || _controller.Config != _config)
            _controller = new CreatureVariantLabController(_state, _config);
    }

    private void LoadStatusDefinitions()
    {
        _controller?.LoadStatusDefinitions(_statusDefinitions, _statusNames);
        _selectedStatusIndex = _controller?.ResolveSelectedStatusIndex(_state.statusDefinition, _statusDefinitions) ?? 0;
    }

    private void Validate()
    {
        _controller?.Validate();
        if (_controller != null && _state != null)
        {
            _selectedStatusIndex = _controller.ResolveSelectedStatusIndex(_state.statusDefinition, _statusDefinitions);
        }
    }

    private void OnPlayModeStateChanged(PlayModeStateChange state)
    {
        _controller?.OnPlayModeStateChanged();
        Repaint();
    }

    private void OnHierarchyChanged() { _controller?.OnHierarchyOrProjectChanged(); Repaint(); }
    private void OnProjectChanged() { LoadStatusDefinitions(); Repaint(); }
    private void OnSceneChanged(Scene prev, Scene next) { Repaint(); }
    private void OnActiveSceneChanged(Scene prev, Scene next) { Repaint(); }

    private void OnGUI()
    {
        if (_headerStyle == null)
            _headerStyle = new GUIStyle(EditorStyles.boldLabel) { fontSize = 15 };

        GUILayout.Space(8);
        GUILayout.Label("Creature Variant Lab", _headerStyle);

        if (_config == null)
        {
            DrawSetupPanel_MissingOrMultiple();
            return;
        }

        var configStatus = _controller?.GetConfigStatus() ?? CreatureVariantLabConfigValidator.ConfigStatus.Missing;
        if (configStatus == CreatureVariantLabConfigValidator.ConfigStatus.Incomplete)
        {
            DrawSetupPanel_Incomplete();
            return;
        }

        EditorGUILayout.LabelField(_controller?.GetCompactStatus() ?? "Ready.", EditorStyles.miniLabel);

        GUILayout.Space(6);
        _scrollPosition = GUILayout.BeginScrollView(_scrollPosition);

        DrawChooseCreatureStep();
        GUILayout.Space(8);
        DrawBuildSkillStep();
        GUILayout.Space(8);
        DrawValidationStep();
        GUILayout.Space(8);
        DrawTestStep();
        GUILayout.Space(8);
        DrawDebugCombatStep();
        GUILayout.Space(12);
        DrawAdvancedTools();

        if (!string.IsNullOrEmpty(_actionFeedback))
            EditorGUILayout.LabelField(_actionFeedback.Replace("\n", "  "), EditorStyles.wordWrappedMiniLabel);

        GUILayout.EndScrollView();
    }

    private void DrawSetupPanel_MissingOrMultiple()
    {
        EditorGUILayout.HelpBox("Setup Required", MessageType.Warning);
        GUILayout.Space(4);

        string[] paths = CreatureVariantAssetService.FindConfigAssetPaths();
        if (paths != null && paths.Length > 1)
        {
            EditorGUILayout.HelpBox("Multiple CreatureVariantLabConfig assets found. Remove duplicates to use the Lab.", MessageType.Error);
            for (int i = 0; i < paths.Length; i++)
            {
                EditorGUILayout.LabelField($"  {paths[i]}", EditorStyles.miniLabel);
                EditorGUILayout.BeginHorizontal();
                if (GUILayout.Button("Select", GUILayout.Width(60)))
                {
                    var obj = AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(paths[i]);
                    if (obj != null) { EditorGUIUtility.PingObject(obj); UnityEditor.Selection.activeObject = obj; }
                }
                if (GUILayout.Button("Delete", GUILayout.Width(60)))
                {
                    AssetDatabase.DeleteAsset(paths[i]);
                    LoadConfig();
                    EnsureController();
                    Validate();
                    Repaint();
                    break;
                }
                EditorGUILayout.EndHorizontal();
            }
        }
        else
        {
            EditorGUILayout.HelpBox("No CreatureVariantLabConfig found. Click below to create one with default presets.", MessageType.Info);
        }

        DrawCreateConfigButton();
    }

    private void DrawSetupPanel_Incomplete()
    {
        EditorGUILayout.HelpBox("Setup Required — Config is incomplete. Fix the issues below before using the Lab.", MessageType.Warning);
        GUILayout.Space(4);

        var errors = _controller?.GetValidationErrorMessages();
        if (errors != null)
        {
            for (int i = 0; i < errors.Count; i++)
                EditorGUILayout.HelpBox(errors[i], MessageType.Error);
        }

        GUILayout.Space(8);

        bool hasMissingPresets = false;
        bool hasInvalidStats = false;
        if (_config != null)
        {
            var missing = CreatureVariantLabConfigValidator.GetMissingPresets(_config);
            hasMissingPresets = missing.Count > 0;
            hasInvalidStats = CreatureVariantLabConfigValidator.HasInvalidPresetStats(_config);
        }

        if (hasMissingPresets)
        {
            if (GUILayout.Button("Create Missing Default Presets", GUILayout.Height(26)))
            {
                CreatureVariantAssetService.EnsureDefaultPresets(_config);
                LoadConfig();
                EnsureController();
                Validate();
                Repaint();
            }
        }

        if (hasInvalidStats)
        {
            if (GUILayout.Button("Repair Invalid Presets", GUILayout.Height(26)))
            {
                CreatureVariantAssetService.RepairInvalidPresetDefaults(_config);
                LoadConfig();
                EnsureController();
                Validate();
                Repaint();
            }
        }

        GUILayout.Space(4);

        EditorGUILayout.BeginHorizontal();
        if (GUILayout.Button("Select Config Asset", GUILayout.Height(24)))
        {
            EditorGUIUtility.PingObject(_config);
            UnityEditor.Selection.activeObject = _config;
        }
        if (GUILayout.Button("Open Config Inspector", GUILayout.Height(24)))
        {
            EditorGUIUtility.PingObject(_config);
            UnityEditor.Selection.activeObject = _config;
        }
        EditorGUILayout.EndHorizontal();

        GUILayout.Space(4);
        if (GUILayout.Button("Regenerate All Default Presets", GUILayout.Height(24)))
        {
            if (EditorUtility.DisplayDialog("Regenerate All Presets",
                "This will reset all preset values to defaults. Existing valid values will be overwritten.\n\nContinue?",
                "Yes, Regenerate", "Cancel"))
            {
                CreatureVariantAssetService.RegenerateAllDefaultPresets(_config);
                LoadConfig();
                EnsureController();
                Validate();
                Repaint();
            }
        }

        GUILayout.Space(4);
        if (GUILayout.Button("Refresh", GUILayout.Height(24)))
        {
            LoadConfig();
            EnsureController();
            Validate();
            Repaint();
        }
    }

    private void DrawCreateConfigButton()
    {
        if (GUILayout.Button("Create Default Config", GUILayout.Height(28)))
        {
            _config = CreatureVariantAssetService.CreateOrFindConfig();
            EnsureController();
            Validate();
            Repaint();
        }
    }

    private void DrawChooseCreatureStep()
    {
        EditorGUILayout.BeginVertical(EditorStyles.helpBox);
        EditorGUILayout.LabelField("1. Choose Creature", EditorStyles.boldLabel);

        EditorGUI.BeginChangeCheck();
        _state.faction = (UnitFaction)EditorGUILayout.EnumPopup(new GUIContent("Faction", Tips.Faction), _state.faction);
        if (_state.faction != UnitFaction.Human && _state.faction != UnitFaction.Orc)
            _state.faction = UnitFaction.Human;
        _state.role = (UnitRole)EditorGUILayout.EnumPopup(new GUIContent("Role", Tips.Role), _state.role);
        _state.team = (UnitTeam)EditorGUILayout.EnumPopup(new GUIContent("Team", Tips.Team), _state.team);

        var preset = _config.GetPreset(_state.faction, _state.role);
        EditorGUI.BeginDisabledGroup(preset == null);
        if (GUILayout.Button("Load Preset Defaults", GUILayout.Height(22)))
        {
            _controller?.LoadDefaultsFromPreset();
            Validate();
        }
        EditorGUI.EndDisabledGroup();
        if (preset == null)
            EditorGUILayout.LabelField("No preset available for this faction/role.", EditorStyles.miniLabel);

        _state.unitName = EditorGUILayout.TextField(new GUIContent("Unit Name", Tips.UnitName), _state.unitName);

        GameObject prefab = _controller.ResolvePrefab();
        if (prefab != null)
            EditorGUILayout.LabelField($"Using prefab: {prefab.name}", EditorStyles.miniLabel);
        else
            EditorGUILayout.LabelField("Using generated placeholder (no prefab override assigned)", EditorStyles.miniLabel);

        _showAdvancedOverrides = EditorGUILayout.Foldout(_showAdvancedOverrides, "Advanced Overrides", true);
        if (_showAdvancedOverrides)
        {
            EditorGUI.indentLevel++;
            _state.prefabOverride = (GameObject)EditorGUILayout.ObjectField(new GUIContent("Prefab", Tips.PrefabOverride), _state.prefabOverride, typeof(GameObject), false);
            EditorGUI.indentLevel--;
        }

        EditorGUILayout.Space(4);
        EditorGUILayout.LabelField("Import", EditorStyles.miniLabel);
        _state.importSource = (UnitData)EditorGUILayout.ObjectField(new GUIContent("Import From", Tips.ImportUnit), _state.importSource, typeof(UnitData), false);
        if (_state.importSource != null)
        {
            if (GUILayout.Button("Import Stats From Selected UnitData", GUILayout.Height(22)))
            {
                _controller.ImportFromExistingUnitData(_state.importSource);
                _state.importSource = null;
                SetFeedback("Imported stats from existing UnitData.", MessageType.Info);
            }
        }

        EditorGUILayout.Space(4);
        _showUnitStats = EditorGUILayout.Foldout(_showUnitStats, "Unit Stats", true);
        if (_showUnitStats)
        {
            EditorGUI.indentLevel++;
            _state.maxHealth = EditorGUILayout.IntField(new GUIContent("Max HP", Tips.MaxHp), _state.maxHealth);
            _state.attackDamage = EditorGUILayout.IntField(new GUIContent("Damage", Tips.Damage), _state.attackDamage);
            _state.defense = EditorGUILayout.IntField(new GUIContent("Defense", Tips.Defense), _state.defense);
            _state.moveSpeed = EditorGUILayout.FloatField(new GUIContent("Move Speed", Tips.MoveSpeed), _state.moveSpeed);
            _state.attackRangeInCells = EditorGUILayout.IntField(new GUIContent("Attack Range", Tips.AttackRange), _state.attackRangeInCells);
            _state.attackCooldown = EditorGUILayout.FloatField(new GUIContent("Attack Cooldown", Tips.AttackCooldown), _state.attackCooldown);
            _state.preferredDistanceInCells = EditorGUILayout.IntField("Preferred Distance", _state.preferredDistanceInCells);
            _state.accuracy = EditorGUILayout.Slider(new GUIContent("Accuracy", Tips.Accuracy), _state.accuracy, 0f, 1f);
            _state.evasion = EditorGUILayout.Slider(new GUIContent("Evasion", Tips.Evasion), _state.evasion, 0f, 1f);
            _state.visionRange = EditorGUILayout.FloatField(new GUIContent("Vision Range", Tips.VisionRange), _state.visionRange);
            _state.combatStyle = (UnitCombatStyle)EditorGUILayout.EnumPopup("Combat Style", _state.combatStyle);
            _state.targetingMode = (UnitTargetingMode)EditorGUILayout.EnumPopup("Targeting Mode", _state.targetingMode);
            _state.manaCostToRecruit = EditorGUILayout.IntField(new GUIContent("Mana Recruit", Tips.ManaRecruit), _state.manaCostToRecruit);
            _state.manaCostToAbsorbSoul = EditorGUILayout.IntField(new GUIContent("Mana Absorb", Tips.ManaAbsorb), _state.manaCostToAbsorbSoul);
            EditorGUI.indentLevel--;
        }

        if (EditorGUI.EndChangeCheck())
            Validate();
        EditorGUILayout.EndVertical();
    }

    private void DrawBuildSkillStep()
    {
        EditorGUILayout.BeginVertical(EditorStyles.helpBox);
        EditorGUILayout.LabelField("2. Build Skill", EditorStyles.boldLabel);

        EditorGUI.BeginChangeCheck();
        _state.delivery = (ImpactPattern)EditorGUILayout.EnumPopup(new GUIContent("Delivery", Tips.Delivery), _state.delivery);
        _state.primaryTarget = (PrimaryTargetRequirement)EditorGUILayout.EnumPopup(new GUIContent("Target", Tips.PrimaryTarget), _state.primaryTarget);
        LabEffectKind previousEffect = _state.effect;
        _state.effect = (LabEffectKind)EditorGUILayout.EnumPopup(new GUIContent("Effect", Tips.Effect), _state.effect);
        _state.modifier = (LabModifierKind)EditorGUILayout.EnumPopup(new GUIContent("Modifier", Tips.Modifier), _state.modifier);

        if (_state.effect != previousEffect)
        {
            _controller.OnEffectChanged(previousEffect, _state.effect, _statusDefinitions);
            _selectedStatusIndex = _controller.ResolveSelectedStatusIndex(_state.statusDefinition, _statusDefinitions);
        }

        if (SkillCompositionMapper.HasNumericValue(_state.effect))
        {
            string valueLabel = _state.effect == LabEffectKind.Damage ? "Damage" :
                _state.effect == LabEffectKind.Heal || _state.effect == LabEffectKind.HealOverTime ? "Heal" : "Shield";
            _state.value = EditorGUILayout.IntField(new GUIContent(valueLabel, Tips.Value), _state.value);
        }

        bool usesStatus = SkillCompositionMapper.IsStatusEffect(_state.effect);
        if (usesStatus)
        {
            EditorGUI.BeginChangeCheck();
            _selectedStatusIndex = EditorGUILayout.Popup(new GUIContent("Status", Tips.Status), _selectedStatusIndex, _statusNames.ToArray());
            if (EditorGUI.EndChangeCheck())
            {
                _state.statusDefinition = _controller.ResolveStatusDefinition(_selectedStatusIndex, _statusDefinitions);
            }

            if (_state.statusDefinition == null)
            {
                string autoResolveMsg = _controller.GetStatusAutoResolveMessage(_state.effect, _statusDefinitions);
                if (!string.IsNullOrEmpty(autoResolveMsg))
                {
                    MessageType msgType = autoResolveMsg.Contains("No StatusEffectDefinition found") ? MessageType.Error : MessageType.Warning;
                    EditorGUILayout.HelpBox(autoResolveMsg, msgType);
                }
            }
        }
        if (usesStatus || _state.effect == LabEffectKind.Shield)
            _state.duration = EditorGUILayout.FloatField(new GUIContent("Duration", Tips.Duration), _state.duration);
        if (_state.effect == LabEffectKind.PoisonBurn || _state.effect == LabEffectKind.HealOverTime)
            _state.interval = EditorGUILayout.FloatField(new GUIContent("Tick Interval", Tips.Interval), _state.interval);
        if (_state.delivery == ImpactPattern.Area)
            _state.radiusInCells = EditorGUILayout.IntField(new GUIContent("Radius", Tips.Radius), _state.radiusInCells);
        if (_state.delivery == ImpactPattern.Line)
            _state.lineLengthInCells = EditorGUILayout.IntField(new GUIContent("Line Length", Tips.LineLength), _state.lineLengthInCells);
        if (_state.primaryTarget != PrimaryTargetRequirement.Self && _state.primaryTarget != PrimaryTargetRequirement.None)
            _state.rangeInCells = EditorGUILayout.IntField(new GUIContent("Range", Tips.Range), _state.rangeInCells);
        if (_state.effect == LabEffectKind.Knockback)
            _state.knockbackCells = EditorGUILayout.IntField(new GUIContent("Knockback Cells", Tips.Knockback), _state.knockbackCells);
        if (_state.effect == LabEffectKind.Summon)
        {
            _state.summonedUnit = (UnitData)EditorGUILayout.ObjectField(new GUIContent("Summon Unit", Tips.SummonedUnit), _state.summonedUnit, typeof(UnitData), false);
            _state.summonAnchorMode = (SummonAnchorMode)EditorGUILayout.EnumPopup(new GUIContent("Summon Anchor", Tips.SummonAnchor), _state.summonAnchorMode);
        }
        if (_state.modifier == LabModifierKind.Bounce)
        {
            _state.bounceMaxBounces = EditorGUILayout.IntField(new GUIContent("Max Bounces", Tips.BounceCount), _state.bounceMaxBounces);
            _state.bounceRangeInCells = EditorGUILayout.IntField(new GUIContent("Bounce Range", Tips.BounceRange), _state.bounceRangeInCells);
            _state.bounceCanBounceToPrimaryTargetAgain = EditorGUILayout.Toggle(new GUIContent("Can Bounce To Primary", Tips.BouncePrimary), _state.bounceCanBounceToPrimaryTargetAgain);
        }
        if (_state.modifier == LabModifierKind.Explosive)
        {
            _state.explosiveRadiusInCells = EditorGUILayout.IntField(new GUIContent("Explosion Radius", Tips.ExplosiveRadius), _state.explosiveRadiusInCells);
            _state.explosiveIncludePrimaryImpactTarget = EditorGUILayout.Toggle(new GUIContent("Include Primary Target", Tips.ExplosivePrimary), _state.explosiveIncludePrimaryImpactTarget);
        }

        if (EditorGUI.EndChangeCheck())
            Validate();
        EditorGUILayout.EndVertical();
    }

    private void DrawValidationStep()
    {
        EditorGUILayout.BeginVertical(EditorStyles.helpBox);
        EditorGUILayout.LabelField("3. Validate", EditorStyles.boldLabel);

        var allIssues = _controller?.ValidationIssues;
        var configErrors = new List<string>();
        var compErrors = new List<string>();
        var warnings = new List<string>();

        if (allIssues != null)
        {
            for (int i = 0; i < allIssues.Count; i++)
            {
                var issue = allIssues[i];
                if (issue.severity == ValidationSeverity.Error)
                {
                    if (issue.category == ValidationCategory.Config)
                        configErrors.Add(issue.message);
                    else
                        compErrors.Add(issue.message);
                }
                else if (issue.severity == ValidationSeverity.Warning)
                {
                    if (issue.category != ValidationCategory.Production)
                        warnings.Add(issue.message);
                }
            }
        }

        if (compErrors.Count == 0 && configErrors.Count == 0)
            EditorGUILayout.HelpBox("Ready to test.", MessageType.Info);
        else
        {
            for (int i = 0; i < compErrors.Count; i++)
                EditorGUILayout.HelpBox(compErrors[i], MessageType.Error);
        }

        if (warnings.Count > 0)
        {
            _showAdvancedWarnings = EditorGUILayout.Foldout(_showAdvancedWarnings, $"Warnings ({warnings.Count})", true);
            if (_showAdvancedWarnings)
            {
                EditorGUI.indentLevel++;
                for (int i = 0; i < warnings.Count; i++)
                    EditorGUILayout.LabelField(warnings[i], EditorStyles.wordWrappedMiniLabel);
                EditorGUI.indentLevel--;
            }
        }
        EditorGUILayout.EndVertical();
    }

    private void DrawTestStep()
    {
        EditorGUILayout.BeginVertical(EditorStyles.helpBox);
        EditorGUILayout.LabelField("4. Test in Scene", EditorStyles.boldLabel);

        if (!EditorApplication.isPlaying)
        {
            EditorGUILayout.LabelField("Enter Play Mode to spawn and test this creature.", EditorStyles.wordWrappedLabel);
        }
        else
        {
            string spawnReason = _controller?.GetSpawnBlockReason();
            if (!string.IsNullOrEmpty(spawnReason))
                EditorGUILayout.HelpBox(spawnReason, MessageType.Warning);

            string sceneReady = _controller?.GetSceneReadinessReport();
            if (!string.IsNullOrEmpty(sceneReady))
                EditorGUILayout.HelpBox(sceneReady, MessageType.Warning);
        }

        EditorGUILayout.LabelField("Lab-spawned units are passive. Use Debug Combat actions to force skill casts.", EditorStyles.wordWrappedMiniLabel);
        EditorGUILayout.LabelField($"Test unit will spawn as: {_state.team}", EditorStyles.miniLabel);

        string spawnBlock = _controller?.GetSpawnBlockReason();
        EditorGUI.BeginDisabledGroup(!string.IsNullOrEmpty(spawnBlock));
        if (GUILayout.Button(new GUIContent("Spawn Test Unit", Tips.SpawnUnit), GUILayout.Height(32)))
            DoSpawn();
        EditorGUI.EndDisabledGroup();

        string dummyBlock = _controller?.GetDummySpawnBlockReason();
        string unitsBlock = _controller?.GetSpawnedUnitsBlockReason();
        EditorGUILayout.BeginHorizontal();
        EditorGUI.BeginDisabledGroup(!string.IsNullOrEmpty(dummyBlock));
        if (GUILayout.Button(new GUIContent("Spawn Target Dummy", Tips.SpawnDummy), GUILayout.Height(26)))
            DoSpawnDummy();
        EditorGUI.EndDisabledGroup();
        EditorGUILayout.LabelField($"Dummy will spawn as: {GetOppositeTeam(_state.team)}", EditorStyles.miniLabel);
        EditorGUILayout.LabelField("Dummy spawns near the test unit for manual skill casting.", EditorStyles.wordWrappedMiniLabel);
        EditorGUI.BeginDisabledGroup(!string.IsNullOrEmpty(unitsBlock));
        if (GUILayout.Button(new GUIContent("Clear Test Units", Tips.ClearUnits), GUILayout.Height(26)))
            DoClearUnits();
        EditorGUI.EndDisabledGroup();
        EditorGUILayout.EndHorizontal();

        if (_controller != null && _controller.IsUsingPlaceholderPrefab() && EditorApplication.isPlaying)
            EditorGUILayout.LabelField("Using placeholder prefab (no prefab override assigned).", EditorStyles.miniLabel);
        if (_controller != null && _controller.IsUsingPlaceholderDummy() && EditorApplication.isPlaying)
            EditorGUILayout.LabelField("Using placeholder dummy (no dummy prefab override assigned).", EditorStyles.miniLabel);

        DrawSpawnSummary();
        _showRuntimeDetails = EditorGUILayout.Foldout(_showRuntimeDetails, "Runtime Details", true);
        if (_showRuntimeDetails && _controller != null)
            DrawSpawnedRuntimeUnits();
        EditorGUILayout.EndVertical();
    }

    private void DrawDebugCombatStep()
    {
        EditorGUILayout.BeginVertical(EditorStyles.helpBox);
        EditorGUILayout.LabelField("5. Debug Combat", EditorStyles.boldLabel);
        EditorGUILayout.LabelField("Use CreatureCombatDebugTool in the Inspector to force charge, cast skills and inspect combat.", EditorStyles.wordWrappedMiniLabel);

        CreatureCombatDebugTool debugTool = _controller?.SceneService?.DebugTool;
        EditorGUI.BeginDisabledGroup(debugTool == null);
        if (GUILayout.Button("Select Debug Tool", GUILayout.Height(22)) && debugTool != null)
        {
            UnityEditor.Selection.activeObject = debugTool.gameObject;
            EditorGUIUtility.PingObject(debugTool.gameObject);
        }
        EditorGUI.EndDisabledGroup();
        EditorGUILayout.EndVertical();
    }

    private void DrawAdvancedTools()
    {
        _showAdvancedTools = EditorGUILayout.Foldout(_showAdvancedTools, "Advanced");
        if (!_showAdvancedTools) return;

        EditorGUI.indentLevel++;
        int tempCount = _controller?.GetLabTempAssetCount() ?? 0;
        if (tempCount > 0)
        {
            EditorGUILayout.LabelField($"Legacy temp assets: {tempCount}", EditorStyles.miniLabel);
            if (GUILayout.Button(new GUIContent("Clear Legacy Temp Assets", Tips.ClearLegacyTemp)))
            {
                int count = _controller?.ClearLabTempAssets() ?? 0;
                SetFeedback($"Cleared {count} legacy temp asset(s).", MessageType.Info);
            }
        }
        if (GUILayout.Button(new GUIContent("Log Runtime State", Tips.LogState)))
        {
            var debugTool = _controller?.SceneService?.DebugTool;
            if (debugTool != null)
                debugTool.LogCurrentState();
            SetFeedback("Logged runtime state to Console.", MessageType.Info);
        }
        EditorGUI.indentLevel--;
    }

    private void DrawSpawnSummary()
    {
        if (_controller == null) return;
        _controller.SceneService.GetSpawnedTeamCounts(out int allies, out int enemies, out int dummies);
        if (allies + enemies + dummies == 0) return;

        string summary = "Spawned: ";
        if (allies > 0) summary += $"{allies} Ally  ";
        if (enemies > 0) summary += $"{enemies} Enemy  ";
        if (dummies > 0) summary += $"{dummies} Dummy";
        EditorGUILayout.LabelField(summary.TrimEnd(), EditorStyles.miniBoldLabel);
    }

    private void DrawSpawnedRuntimeUnits()
    {
        EditorGUILayout.BeginVertical("box");
        var debugTool = _controller?.SceneService?.DebugTool;
        if (debugTool == null || debugTool.SpawnedUnits.Count == 0)
        {
            EditorGUILayout.HelpBox("No spawned units yet. Spawn a test unit from Runtime Test Actions.", MessageType.Info);
            EditorGUILayout.EndVertical();
            return;
        }

        DrawTeamGroup(debugTool, UnitTeam.Ally, "Allies");
        DrawTeamGroup(debugTool, UnitTeam.Enemy, "Enemies and Dummies");
        EditorGUILayout.EndVertical();
    }

    private void DrawTeamGroup(CreatureCombatDebugTool debugTool, UnitTeam team, string heading)
    {
        bool drewHeading = false;
        for (int i = 0; i < debugTool.SpawnedUnits.Count; i++)
        {
            Unit unit = debugTool.SpawnedUnits[i];
            if (unit == null || unit.Team != team) continue;

            if (!drewHeading)
            {
                EditorGUILayout.LabelField(heading, EditorStyles.boldLabel);
                drewHeading = true;
            }

            UnitMovement movement = unit.GetComponent<UnitMovement>();
            string cell = movement != null && movement.TryGetLogicalCell(out Vector3Int logicalCell)
                ? $"({logicalCell.x}, {logicalCell.y})"
                : "Unknown";
            SkillCaster caster = unit.GetComponent<SkillCaster>();
            string charge = caster != null ? $"{caster.CurrentCharge:F0}/{caster.MaxCharge:F0}" : "N/A";
            string state = unit.IsAlive ? "Alive" : "Dead";

            EditorGUILayout.BeginHorizontal(EditorStyles.helpBox);
            EditorGUILayout.LabelField(new GUIContent(unit.name, "Runtime unit created by Creature Variant Lab."),
                $"{team} | Cell {cell} | {state} | HP {unit.CurrentHealth}/{unit.MaxHealth} | Charge {charge}");
            if (GUILayout.Button(new GUIContent("Select", Tips.SelectUnit), GUILayout.Width(58)))
            {
                UnityEditor.Selection.activeObject = unit.gameObject;
                EditorGUIUtility.PingObject(unit.gameObject);
                SetFeedback($"Selected spawned unit: {unit.name}", MessageType.Info);
            }
            EditorGUILayout.EndHorizontal();
        }
    }

    private void DoSpawn()
    {
        string error = _controller?.SpawnTestUnit();
        if (!string.IsNullOrEmpty(error))
            EditorUtility.DisplayDialog("Cannot Spawn", error, "OK");
        else
            Repaint();
    }

    private void DoSpawnDummy()
    {
        string error = _controller?.SpawnDummy();
        if (!string.IsNullOrEmpty(error))
            EditorUtility.DisplayDialog("Cannot Spawn Dummy", error, "OK");
        else
            Repaint();
    }

    private static UnitTeam GetOppositeTeam(UnitTeam team)
    {
        return team == UnitTeam.Ally ? UnitTeam.Enemy : UnitTeam.Ally;
    }

    private void DoClearUnits()
    {
        _controller?.ClearSpawnedUnits();
        SetFeedback("Cleared spawned units.", MessageType.Info);
    }

    private void SetFeedback(string message, MessageType type)
    {
        _actionFeedback = message;
        _actionFeedbackType = type;
        Repaint();
    }
}