using UnityEditor;
using UnityEngine;

public static class CreatureVariantBuilder
{
    public static void ConfigureSkillData(SkillData skill, CreatureVariantLabState state, string assetName, string displayName, SkillCompositionState compositionState, CreatureVariantLabConfig config)
    {
        SerializedObject skillSO = new SerializedObject(skill);
        skillSO.FindProperty("_skillId").stringValue = assetName;
        skillSO.FindProperty("_displayName").stringValue = displayName;
        skillSO.FindProperty("_description").stringValue = "Autogenerated skill from the Creature Variant Lab.";

        skillSO.FindProperty("_primaryTargetRequirement").enumValueIndex = (int)state.primaryTarget;
        skillSO.FindProperty("_impactTargetRequirement").enumValueIndex = (int)SkillCompositionResolver.ResolveImpactTargetRequirement(state);
        skillSO.FindProperty("_targetSelectionMode").enumValueIndex = (int)SkillCompositionResolver.ResolveTargetSelectionMode(state);
        skillSO.FindProperty("_targetFallbackMode").enumValueIndex = (int)SkillCompositionResolver.ResolveTargetFallbackMode(state);

        skillSO.FindProperty("_trajectory").enumValueIndex = (int)SkillCompositionResolver.ResolveTrajectory(state);
        skillSO.FindProperty("_impactPattern").enumValueIndex = (int)state.delivery;
        skillSO.FindProperty("_impactCenterMode").enumValueIndex = (int)SkillCompositionResolver.ResolveImpactCenterMode(state);
        skillSO.FindProperty("_skillExecutionMode").enumValueIndex = (int)SkillCompositionResolver.ResolveExecutionMode(state);

        ConfigureCompositionEffects(skillSO, state);
        ConfigureCompositionModifiers(skillSO, state);
        skillSO.FindProperty("_compositionState").enumValueIndex = (int)compositionState;

        skillSO.FindProperty("_castTime").floatValue = 0f;
        skillSO.FindProperty("_rangeInCells").intValue = SkillCompositionResolver.ResolveRangeInCells(state);
        skillSO.FindProperty("_radiusInCells").intValue = state.radiusInCells;
        skillSO.FindProperty("_lineLengthInCells").intValue = state.lineLengthInCells;
        skillSO.FindProperty("_maxTargets").intValue = SkillCompositionResolver.ResolveMaxTargets(state, config);

        skillSO.ApplyModifiedProperties();
    }

    public static void ConfigureUnitData(UnitData unit, CreatureVariantLabState state, SkillData skill, GameObject prefab)
    {
        SerializedObject unitSO = new SerializedObject(unit);
        unitSO.FindProperty("unitPrefab").objectReferenceValue = prefab;
        unitSO.FindProperty("team").enumValueIndex = (int)state.team;
        unitSO.FindProperty("role").enumValueIndex = (int)state.role;
        unitSO.FindProperty("faction").enumValueIndex = (int)state.faction;
        unitSO.FindProperty("combatStyle").enumValueIndex = (int)state.combatStyle;
        unitSO.FindProperty("targetingMode").enumValueIndex = (int)state.targetingMode;
        unitSO.FindProperty("tileSize").intValue = 1;
        unitSO.FindProperty("manaCostToRecruit").intValue = state.manaCostToRecruit;
        unitSO.FindProperty("manaCostToAbsorbSoul").intValue = state.manaCostToAbsorbSoul;

        SerializedProperty statsProp = unitSO.FindProperty("stats");
        statsProp.FindPropertyRelative("maxHealth").intValue = state.maxHealth;
        statsProp.FindPropertyRelative("attackDamage").intValue = state.attackDamage;
        statsProp.FindPropertyRelative("attackCooldown").floatValue = state.attackCooldown;
        statsProp.FindPropertyRelative("attackRangeInCells").intValue = state.attackRangeInCells;
        statsProp.FindPropertyRelative("preferredDistanceInCells").intValue = state.preferredDistanceInCells;
        statsProp.FindPropertyRelative("accuracy").floatValue = state.accuracy;
        statsProp.FindPropertyRelative("evasion").floatValue = state.evasion;
        statsProp.FindPropertyRelative("defense").intValue = state.defense;
        statsProp.FindPropertyRelative("moveSpeed").floatValue = state.moveSpeed;
        statsProp.FindPropertyRelative("visionRange").floatValue = state.visionRange;

        unitSO.FindProperty("unitId").stringValue = CreatureVariantNameSanitizer.SanitizeUnitId(state.unitName);
        unitSO.FindProperty("displayName").stringValue = CreatureVariantNameSanitizer.SanitizeDisplayName(state.unitName);
        unitSO.FindProperty("skill").objectReferenceValue = skill;

        unitSO.ApplyModifiedProperties();
    }

    public static void ApplyDefaultsFromPreset(CreatureVariantLabState state, CreatureVariantLabConfig.FactionRolePreset preset)
    {
        if (preset == null)
            return;

        state.combatStyle = preset.defaultCombatStyle;
        state.targetingMode = preset.defaultTargetingMode;
        state.maxHealth = preset.defaultMaxHealth;
        state.attackDamage = preset.defaultAttackDamage;
        state.attackCooldown = preset.defaultAttackCooldown;
        state.attackRangeInCells = preset.defaultAttackRangeInCells;
        state.preferredDistanceInCells = preset.defaultPreferredDistanceInCells;
        state.accuracy = preset.defaultAccuracy;
        state.evasion = preset.defaultEvasion;
        state.defense = preset.defaultDefense;
        state.moveSpeed = preset.defaultMoveSpeed;
        state.visionRange = preset.defaultVisionRange;
        state.manaCostToRecruit = preset.defaultManaCostToRecruit;
        state.manaCostToAbsorbSoul = preset.defaultManaCostToAbsorbSoul;
    }

    public static void ImportFromExistingUnitData(CreatureVariantLabState state, UnitData source)
    {
        if (source == null)
            return;

        state.unitName = source.displayName;
        state.faction = source.faction;
        state.role = source.role;
        state.team = source.team;
        state.combatStyle = source.combatStyle;
        state.targetingMode = source.targetingMode;
        state.prefabOverride = source.unitPrefab;
        state.manaCostToRecruit = source.manaCostToRecruit;
        state.manaCostToAbsorbSoul = source.manaCostToAbsorbSoul;

        if (source.stats != null)
        {
            state.maxHealth = source.stats.maxHealth;
            state.attackDamage = source.stats.attackDamage;
            state.attackCooldown = source.stats.attackCooldown;
            state.attackRangeInCells = source.stats.attackRangeInCells;
            state.preferredDistanceInCells = source.stats.preferredDistanceInCells;
            state.accuracy = source.stats.accuracy;
            state.evasion = source.stats.evasion;
            state.defense = source.stats.defense;
            state.moveSpeed = source.stats.moveSpeed;
            state.visionRange = source.stats.visionRange;
        }
    }

    public static bool VariantMatchesComposition(UnitData ud, CreatureVariantLabState state, CreatureVariantLabConfig config)
    {
        SkillData sd = ud.skill;
        if (sd == null) return false;

        if (sd.ImpactPattern != state.delivery) return false;
        if (sd.PrimaryTargetRequirement != state.primaryTarget) return false;
        if (sd.ImpactTargetRequirement != SkillCompositionResolver.ResolveImpactTargetRequirement(state)) return false;
        if (sd.TargetSelectionMode != SkillCompositionResolver.ResolveTargetSelectionMode(state)) return false;
        if (sd.ImpactCenterMode != SkillCompositionResolver.ResolveImpactCenterMode(state)) return false;
        if (sd.RangeInCells != SkillCompositionResolver.ResolveRangeInCells(state)) return false;
        if (sd.MaxTargets != SkillCompositionResolver.ResolveMaxTargets(state, config)) return false;

        if (state.delivery == ImpactPattern.Area && sd.RadiusInCells != state.radiusInCells) return false;
        if (state.delivery == ImpactPattern.Line && sd.LineLengthInCells != state.lineLengthInCells) return false;

        if (sd.CompositionEffects == null || sd.CompositionEffects.Length != 1) return false;
        SkillCompositionEffect eff = sd.CompositionEffects[0];

        SkillEffectKind expectedKind = SkillCompositionMapper.ToSkillEffectKind(state.effect);
        if (eff.EffectKind != expectedKind) return false;

        bool isStatus = SkillCompositionMapper.IsStatusEffect(state.effect);
        int expectedValue = state.effect == LabEffectKind.Knockback ? state.knockbackCells : state.value;
        if (!isStatus && eff.Value != expectedValue) return false;
        if (state.effect == LabEffectKind.Shield && !Mathf.Approximately(eff.Duration, state.duration)) return false;

        if (isStatus && eff.StatusDefinition != state.statusDefinition) return false;
        if (state.effect == LabEffectKind.Summon && (eff.SummonedUnit != state.summonedUnit || eff.SummonAnchorMode != state.summonAnchorMode)) return false;

        if (state.modifier == LabModifierKind.None)
        {
            if (sd.CompositionModifierKinds != null && sd.CompositionModifierKinds.Length > 0) return false;
        }
        else
        {
            if (sd.CompositionModifierKinds == null || sd.CompositionModifierKinds.Length != 1) return false;

            SkillModifierKind expectedMod = SkillCompositionMapper.ToSkillModifierKind(state.modifier);
            if (sd.CompositionModifierKinds[0] != expectedMod) return false;

            if (expectedMod == SkillModifierKind.Bounce || expectedMod == SkillModifierKind.Explosive)
            {
                if (sd.CompositionModifierData == null || sd.CompositionModifierData.Length == 0) return false;
                bool modDataMatch = false;
                foreach (var md in sd.CompositionModifierData)
                {
                    if (md.ModifierKind == expectedMod)
                    {
                        if (expectedMod == SkillModifierKind.Bounce)
                        {
                            if (md.BounceMaxBounces == state.bounceMaxBounces &&
                                md.BounceRangeInCells == state.bounceRangeInCells &&
                                md.BounceCanBounceToPrimaryTargetAgain == state.bounceCanBounceToPrimaryTargetAgain)
                                modDataMatch = true;
                        }
                        else if (expectedMod == SkillModifierKind.Explosive)
                        {
                            if (md.ExplosiveRadiusInCells == state.explosiveRadiusInCells &&
                                md.ExplosiveIncludePrimaryImpactTarget == state.explosiveIncludePrimaryImpactTarget)
                                modDataMatch = true;
                        }
                    }
                }
                if (!modDataMatch) return false;
            }
        }

        return true;
    }

    private static void ConfigureCompositionEffects(SerializedObject skillSO, CreatureVariantLabState state)
    {
        SerializedProperty effectsProp = skillSO.FindProperty("_compositionEffects");
        effectsProp.arraySize = 1;
        SerializedProperty effectProp = effectsProp.GetArrayElementAtIndex(0);

        SkillEffectKind kind = SkillCompositionMapper.ToSkillEffectKind(state.effect);
        effectProp.FindPropertyRelative("_effectKind").enumValueIndex = (int)kind;

        bool isStatus = SkillCompositionMapper.IsStatusEffect(state.effect);
        int effectValue = state.effect == LabEffectKind.Knockback ? state.knockbackCells : state.value;
        float effectDuration = isStatus && state.statusDefinition != null
            ? state.statusDefinition.DurationSeconds
            : state.effect == LabEffectKind.Shield ? state.duration : 0f;
        float effectInterval = isStatus && state.statusDefinition != null
            ? state.statusDefinition.TickIntervalSeconds
            : 0f;
        int effectMaxStacks = isStatus && state.statusDefinition != null
            ? state.statusDefinition.MaxStacks
            : 1;

        effectProp.FindPropertyRelative("_value").intValue = effectValue;
        effectProp.FindPropertyRelative("_duration").floatValue = effectDuration;
        effectProp.FindPropertyRelative("_interval").floatValue = effectInterval;
        effectProp.FindPropertyRelative("_maxStacks").intValue = effectMaxStacks;
        effectProp.FindPropertyRelative("_summonedUnit").objectReferenceValue =
            state.effect == LabEffectKind.Summon ? state.summonedUnit : null;
        effectProp.FindPropertyRelative("_statusDefinition").objectReferenceValue =
            isStatus ? state.statusDefinition : null;
        effectProp.FindPropertyRelative("_summonAnchorMode").enumValueIndex = (int)state.summonAnchorMode;
    }

    private static void ConfigureCompositionModifiers(SerializedObject skillSO, CreatureVariantLabState state)
    {
        if (state.modifier != LabModifierKind.None)
        {
            SerializedProperty modifierKindsProp = skillSO.FindProperty("_compositionModifierKinds");
            modifierKindsProp.arraySize = 1;

            SkillModifierKind modKind = SkillCompositionMapper.ToSkillModifierKind(state.modifier);
            modifierKindsProp.GetArrayElementAtIndex(0).enumValueIndex = (int)modKind;

            SerializedProperty modifierDataProp = skillSO.FindProperty("_compositionModifierData");
            modifierDataProp.arraySize = 1;
            SerializedProperty modDataProp = modifierDataProp.GetArrayElementAtIndex(0);
            modDataProp.FindPropertyRelative("_modifierKind").enumValueIndex = (int)modKind;
            modDataProp.FindPropertyRelative("_bounceMaxBounces").intValue = state.bounceMaxBounces;
            modDataProp.FindPropertyRelative("_bounceRangeInCells").intValue = state.bounceRangeInCells;
            modDataProp.FindPropertyRelative("_bounceCanBounceToPrimaryTargetAgain").boolValue = state.bounceCanBounceToPrimaryTargetAgain;
            modDataProp.FindPropertyRelative("_explosiveRadiusInCells").intValue = state.explosiveRadiusInCells;
            modDataProp.FindPropertyRelative("_explosiveIncludePrimaryImpactTarget").boolValue = state.explosiveIncludePrimaryImpactTarget;
        }
        else
        {
            skillSO.FindProperty("_compositionModifierKinds").arraySize = 0;
            skillSO.FindProperty("_compositionModifierData").arraySize = 0;
        }
    }
}